// <auto-generated />
namespace AllShare.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_IdentityOff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_IdentityOff));
        
        string IMigrationMetadata.Id
        {
            get { return "201602232123443_User_IdentityOff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
